name: Assign reviewers

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  AssignReviewers:
    name: Assign reviewers
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Assign reviewers based upon files changed
        uses: shufo/auto-assign-reviewer-by-files@v1.1.2
        with:
          config: "./codeowners/assign-by-files.yml"
          token: ${{ secrets.GITHUB_TOKEN }}
