# Workflow to assign CODEOWNERS as reviewers
# Finalised, will run independently of others
name: Assign reviewers

on:
  # be cautious with pull_request_target
  pull_request_target:
    branches: [ main ]
    types:
      [ opened, ready_for_review, synchronize ]

jobs:
  AssignReviewers:
    name: Assign reviewers

    runs-on: ubuntu-latest

    steps:
      - name: Assign reviewers based upon files changed
        uses: necojackarc/auto-request-review@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: docs/pr-reviewers.yml
