# This is a basic workflow to help you get started with Actions

name: ESLint

# Controls when the workflow will run
on: [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ESLintCheck:
    # The type of runner that the job will run on
    name: ESLint check
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
      
      - run: npm ci

      - run: npm i -g eslint

      - name: ESLint check
        run: eslint . --ext .js,.jsx,.ts,.tsx
