name: gh-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  RunTests:
    name: Run Tests
    uses: MessageBottle/crew/.github/workflows/test.yml@main

  UpdateGHPages:
    name: Update gh-pages branch

    runs-on: ubuntu-latest

    needs: [ RunTests ]

    environment: github-pages

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - run: |
          echo 'REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}' >> envfiles/.env
          echo 'REACT_APP_AUTH_DOMAIN=${{ secrets.REACT_APP_AUTH_DOMAIN }}' >> envfiles/.env
          echo 'REACT_APP_DATABASE_URL=${{ secrets.REACT_APP_DATABASE_URL }}' >> envfiles/.env
          echo 'REACT_APP_PROJECT_ID=${{ secrets.REACT_APP_PROJECT_ID }}' >> envfiles/.env
          echo 'REACT_APP_STORAGE_BUCKET=${{ secrets.REACT_APP_STORAGE_BUCKET }}' >> envfiles/.env
          echo 'REACT_APP_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}' >> envfiles/.env
          echo 'REACT_APP_APP_ID=${{ secrets.REACT_APP_APP_ID }}' >> envfiles/.env
          echo 'REACT_APP_MEASUREMENT_ID=${{ secrets.REACT_APP_MEASUREMENT_ID }}' >> envfiles/.env

      - run: npm run build

      - name: Push build to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          commit_message: ${{ github.event.head_commit.message }}
