name: Review PR

on: [ push, pull_request ]

jobs:

  MisspellCheck:
    name: Misspell check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Review Dog
        uses: reviewdog/action-misspell@v1.9.0
        with:
          reporter: github-pr-review
          level: warning
