# Workflow to assign an issue to yourself
# Finalised, will run independently of others
name: Take issue
on: 
  issue_comment:
    types: [ created, edited ]

jobs:
  AssignYourself:
    name: Assign issue to yourself

    runs-on: ubuntu-latest

    steps:
    - name: Assign issue to yourself
      uses: bdougie/take-action@main
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        message: |
          Did someone just request for `.take` ? :astonished:. Mm-hmm . . . . .&nbsp; interesting :thinking:  
          I sense someone pumped up with enthusiasm :fire::fire:.
