name: Take issue
on: 
  issue_comment:
    types: [ created, edited ]

jobs:
  AssignMyself:
    name: Assign issue to myself

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Assign issue to myself
      uses: bdougie/take-action@main
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        message: |
          Did someone just request for `.take`? :astonished:. Hmmmm......... interesting :thinking:  
          I sense someone pumped up with enthusiasm :fire:. All the best :innocent:.
